# TekMoniOnKill configuration file!

# Step 1. Configure how much money the plugin will take on death. (double)
moneytotake: 10.0
moneytogive: 25.0


# Step 2. (optional) Customize the plugin's messages!
# Set any message to 'none' to disable.

# Message to send to the killer. (String) [Use {1] for the amount of money they'll receive and {2} for the player they killed)
msg.tokiller: You gained {1} credit for killing {2}!

# Message to send to the victim. (String) [Use {1] for the amount of money that has been withdrawn from their account and {2} for the player who killed them)
msg.tovictim: You lost {1} credits for being killed by {2}!

# Message to send if the victim does not have enough money.
msg.notenough: You don't have enough money.
